config/routes.rb
Protsahan::Application.routes.draw do
  root :to => 'articles#show', :id => 'home'
  match '/pages/*id' => 'high_voltage/pages#show', :as => :page, :format => false
  match '/*id' => 'articles#show', :as => :article, :format => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < HighVoltage::PagesController
  layout :get_layout

private
  def get_layout
    return 'application' if ['home'].include? params[:id]
    return 'articles'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auto_page_class_names
    [params[:controller], params[:action], params[:id]].compact.map{ |n| n.split('/') }.flatten
  end
end

app/views/layouts/application.html.haml
- content_for :body do
  %header
    =link_to root_path do
      %h1.offset1
        Protsahan
        %small (n.) Encouragement

    = render 'shared/navigation', class_name: 'nav-list nav-pullout'

  #body= content_for?(:content) ? yield(:content) : yield

  %footer
    %p.pull-center &copy; Protsahan 2012 - Built by #{link_to 'loonyb.in', 'http://loonyb.in'}

= render :template => 'layouts/skeleton'

app/views/layouts/articles.html.haml
- content_for :head do
  :css
    body.articles .leader { background-image: url('#{image_path "#{params[:id]}.jpg"}'); }

- content_for :content do
  .scroll-wrapper
    %section.leader.span8
      %h2.span3
        = yield :title
        %small= yield :caption

    %section.content.span4= yield

= render :template => 'layouts/application'

app/views/layouts/pages.html.haml
- content_for :content do
  .scroll-wrapper
    %section.leader.span9{style: "background-image: url('#{image_path "#{params[:id]}.jpg"}')"}
      %h2.span3
        = yield :title
        %small= yield :caption

    %section.content.span4= yield

= render :template => 'layouts/application'

app/views/layouts/skeleton.html.haml
!!! 5
%html(lang='en')
  %head
    %meta(charset='utf-8')
    %meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    %title= content_for?(:title) ? yield(:title) : 'Protsahan'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    = stylesheet_link_tag 'application', :media => 'all'
    %link(href='images/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144')
    %link(href='images/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114')
    %link(href='images/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72')
    %link(href='images/apple-touch-icon.png' rel='apple-touch-icon-precomposed')
    %link(href='/favicon.ico' rel='shortcut icon')
    = yield :head

  %body{ class: auto_page_class_names }
    = content_for?(:body) ? yield(:body) : yield
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag 'application'
    = yield :js

app/views/pages/gallery.html.haml
- provide :title, 'Gallery'
- content_for :js do
  #modal-gallery.modal.modal-gallery.hide.fade{:tabindex => "-1"}
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3.modal-title
    .modal-body
      .modal-image
    .modal-footer
      %a.btn.btn-success.pull-left.modal-play.modal-slideshow{"data-slideshow" => "5000"}
        %i.icon-play.icon-white
        Slideshow
      %a.btn.pull-left.modal-download{:target => "_blank"}
        %i.icon-download
        Download
      %a.btn.btn-info.modal-prev
        %i.icon-arrow-left.icon-white
        Previous
      %a.btn.btn-primary.modal-next
        Next
        %i.icon-arrow-right.icon-white
  :coffee
    $ ->
      window.router = new Protsahan.Routers.PicasaImagesRouter()
      Backbone.history.start()

app/views/pages/home.html.haml
.container
  .row
    .span8.offset1.center
      .row
        .span8
          .page-header
            %p.caption
              A social enterprise focusing on creative education or skill development by empowering children
              &amp; women at grassroot communities using the five pillars of creativity: Design, Cinema, Stories,
              Photography &amp; Art

      .row
        .span2.stick_figure
          &nbsp;
          = image_tag 'stick_figure.jpg'
        .span6
          #banner.carousel.slide{data: {interval: 2000}}
            .carousel-inner
              = image_tag 'home.jpg', class: %w(item active)
              = image_tag 'gallery.jpg', class: %w(item)
              = image_tag 'contact_us.jpg', class: %w(item)
              = image_tag 'projects/educare.jpg', class: %w(item)
              = image_tag 'about_us/our-team.jpg', class: %w(item)

    .span3.social
      = link_to  page_path('donate'), class: %w(donate btn btn-large btn-block btn-success show-grid) do
        %i.icon-gift
        Donate
      = render 'shared/like_box'

  .row
    .offset1.span11
      %h3 We are supported by
      %ul.thumbnails
        %li.span1= image_tag 'world_bank.jpg', class: :thumbnail
        %li.span2= image_tag 'airtel.png', class: :thumbnail
        %li.span1= image_tag 'pvr_nest.jpg', class: :thumbnail
        %li.span2= image_tag 'loonybin.png', class: :thumbnail

app/views/shared/_navigation.html.haml
%ul.nav{class: class_name}
  %li= link_to 'Gallery', article_path('gallery')
  %li.dropdown
    %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
      About Us
      %b.caret
    %ul.dropdown-menu
      %li= link_to 'Organizational Profile',  article_path('about_us/organizational-profile')
      %li= link_to 'Strategic Focus',         article_path('about_us/strategic-focus')
      %li= link_to 'Our Rationale',           article_path('about_us/our-rationale')
      %li= link_to 'Our Team',                article_path('about_us/our-team')
      %li= link_to 'Work Culture',            article_path('about_us/work-culture')
      %li= link_to 'Recognition Received',    article_path('about_us/recognition-received')
  %li.dropdown
    %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
      Projects
      %b.caret
    %ul.dropdown-menu
      %li= link_to 'Educare',         article_path('projects/educare')
      %li= link_to 'Stree',           article_path('projects/stree')
      %li= link_to 'Artisan Honour',  article_path('projects/artisan-honour')
  %li= link_to 'Get Involved', article_path('contact_us')